### ISSUE TITLE
Ability to reset

### ISSUE THREAD

**Issue by SantanaJodi** [dopey2/react-scratchcard-v2#1]
Hi, it will be helpful if there is an ability to reset the scratched image. Thankyou 🙌

**Comment by dopey2** [comment]
Closed in bee151f264f53c3c7cff7f9ee6946f47b460885f. 
First upgrade the package version to 1.1.0
Check the [readme.usage](https://github.com/dopey2/react-scratchcard-v2#usage) for usage
