### ISSUE TITLE
URGENT! on complete, function run multiple times

### ISSUE THREAD

**Issue by BelieveInBunny** [dopey2/react-scratchcard-v2#2]
I am having trouble with the function, Function is called multiple time on complete so that it send multiple request. It doesn't stop on first request. Even if I add "If", I have tried number of ways to fix it.
But I am unable to resolve it.

**Comment by BelieveInBunny** [comment]
Making the codepen now, are you on telegram or whatsapp so I can have better discussion

**Comment by dopey2** [comment]
Are you on discord ?

**Comment by BelieveInBunny** [comment]
I am on discord, Avatar#2588

**Comment by dopey2** [comment]
Fixed on aa3e28241a05a41f45d22b00c2d25932e37e1c07

**Comment by BelieveInBunny** [comment]
Working like a charm now, once again really apprecaite all of your help.

**Comment by BelieveInBunny** [comment]
Yay!
